location            = "Central India"
resource_group_name = "rg-monitoring-prod"
vm_name             = "vm-monitoring-prod"
workspace_name      = "law-monitoring-prod"
admin_username      = "azureadmin"
admin_source_cidr   = "116.75.123.113/32"